validator/validator.py
=> Unbound e variable in try/except block

validator/bundler.py
as our pr checks are taking more and more time, this is another performance improvement.
i noticed that at times the bundle creation takes a long time, so this will speed it up a bit.
=> [bundler] parallelise

validator/validator.py
covers https://issues.redhat.com/browse/APPSRE-1299
=> json schema validation for resources

validator/bundler.py
used to expose the git commit in qontract-server
=> add git-commit to bundle

dockerfiles/Dockerfile, dockerfiles/Dockerfile.test, setup.py, tox.ini, validator/bundler.py, validator/validator.py
Update qontract-validator to python3 and use draft06
=> Py3 and draft06

validator/validator.py
This PR introduces a new feature that enforces that a given field must be unique across all the datafiles of the same schema.
The GraphQL schema defined in the bundle now allows users to mark fields with the `isUnique: true` attribute. This will fail the validation the field is repeated.
For example, with this schema:
```yaml
datafile: /app-sre/saas-file-1.yml
name: SaasFile_v1
fields:
- name: name
type: string
isRequired: true
isSearchable: true
isUnique: true
- ...
```
=> APPSRE-2693: Adds feature to enforce unique fields

validator/bundler.py
part of https://issues.redhat.com/browse/APPSRE-2610
this PR adds the git commit timestamp to the bundle.
=> add git_commit_timestamp to bundle

dockerfiles/Dockerfile, dockerfiles/Dockerfile.test
part of https://issues.redhat.com/browse/APPSRE-2821
=> Dockerfile pull from centos/centos

validator/bundler.py
=> Add schema to resources

validator/bundler.py
=> Capture yaml ConstructorErrors too

validator/bundler.py
As we can have lists or plain files
=> Capture all yaml errors + AttributeErrors

validator/bundler.py
=> Capture yaml errors from base error class

validator/bundler.py
We can't use pyyaml to parse jinja2 templated yaml
=> Find the schema in resources via regexp

dockerfiles/Dockerfile, dockerfiles/Dockerfile.test, setup.py, tox.ini
the change has been verified by producing and verifying a bundle before and after the change.
both times a bundle with the exact same file hash was produced
ref: https://issues.redhat.com/browse/APPSRE-5619
Signed-off-by: Gerd Oberlechner <goberlec@redhat.com>
=> update to python 3.9 and ubi 8 minimal

validator/postprocess.py
Signed-off-by: Gerd Oberlechner <goberlec@redhat.com>
=> fixed a bug for resource backref detection in lists

.tool-versions, dockerfiles/Dockerfile, dockerfiles/Dockerfile.test, pyproject.toml, setup.py, tox.ini
=> Upgrade to Python 3.11

validator/bundle.py, validator/bundler.py, validator/postprocess.py
instead of stoping post processing checks after the first error, this PR changes the behaviour to proceed and report all errors collectively at the end
=> report all context-uniqueness issues

.tekton/qontract-validator-master-pull-request.yaml, .tekton/qontract-validator-master-push.yaml
Add tekton files needed to build PRs and master in konflux
=> add tekton files for konflux builds

Dockerfile, LICENSE
- add license to the image
- update to ubi9 9.5
- use python/pip/setuptools from the package manager
- run as a non-root user
=> refactor dockerfile

renovate.json
Add our default renovate config.
=> :construction_worker: add renovate config

.tekton/qontract-validator-master-pull-request.yaml, .tekton/qontract-validator-master-push.yaml
Remove obsolete `ecosystem-cert-preflight-checks` limit requests:
```
[User error] 1 error occurred:
* invalid StepOverride: No Step named check-container
```
=> :green_heart: fix konflux pipeline

.tekton/qontract-validator-master-pull-request.yaml, .tekton/qontract-validator-master-push.yaml
=> :green_heart: ci: konflux service account

validator/bundler.py, validator/utils.py, validator/validator.py
refactor and improve performance of `qontract-validator`:
refactor:
* add typing
* use `TypedDict`
* comprehension
perf:
* use `CSafeLoader` for yaml
* skip `$schema` for non yaml resource files
* streaming process validation
* less indent on json output
for current app-interface data:
* old version: 6s
* new version: 3s
[APPSRE-12074](https://issues.redhat.com/browse/APPSRE-12074)
=> perf: improve validate time

Dockerfile
Fix https://github.com/app-sre/qontract-validator/pull/95#discussion_r2137111651
=> fix: use minimal image as base to avoid missing licence file
